version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/final_kitapsoresi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_MAIN_ALLOW-CIRCULAR-REFERENCES=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=final_kitapsoresi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
